[package]
authors = ['Bholdus']
description = 'Bholdus pallet to crosschain transfer native'
edition = '2018'
homepage = 'https://substrate.dev'
license = 'Unlicense'
name = 'bholdus-bridge-native-transfer'
readme = 'README.md'
repository = 'https://github.com/bholdus/bholdus-chain.git'
version = '4.0.0-dev'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

# Substrate dependencies
[dependencies.codec]
default-features = false
features = ['derive', 'max-encoded-len']
package = 'parity-scale-codec'
version = '2.2.0'

[dependencies.scale-info]
default-features = false
features = ['derive']
version = '1.0'

[dependencies.frame-benchmarking]
default-features = false
git = 'https://github.com/bholdus/substrate.git'
optional = true
branch = 'master'
version = '4.0.0-dev'

[dependencies.frame-support]
default-features = false
git = 'https://github.com/bholdus/substrate.git'
branch = 'master'
version = '4.0.0-dev'

[dependencies.frame-system]
default-features = false
# path = '../frame/system'
git = 'https://github.com/bholdus/substrate.git'
branch = 'master'
version = '4.0.0-dev'

[dev-dependencies]
serde = '1.0.119'
pallet-balances = { version = '4.0.0-dev', git = 'https://github.com/bholdus/substrate.git', branch = 'master' }

[dev-dependencies.sp-core]
default-features = false
git = 'https://github.com/bholdus/substrate.git'
branch = 'master'
version = '4.0.0-dev'

[dev-dependencies.sp-io]
default-features = false
git = 'https://github.com/bholdus/substrate.git'
branch = 'master'
version = '4.0.0-dev'

[dependencies.sp-runtime]
default-features = false
git = 'https://github.com/bholdus/substrate.git'
branch = 'master'
version = '4.0.0-dev'

[dependencies.sp-std]
default-features = false
git = 'https://github.com/bholdus/substrate.git'
branch = 'master'
version = '4.0.0-dev'

[dependencies]
bholdus-primitives = { version = '4.0.0-dev', default-features = false, path = '../../../primitives/bholdus' }


[features]
default = ['std']
runtime-benchmarks = ['frame-benchmarking']
std = [
	'codec/std',
	'scale-info/std',
	'frame-support/std',
	'frame-system/std',
	'frame-benchmarking/std',
	'sp-std/std',
	'bholdus-primitives/std',
]
try-runtime = ['frame-support/try-runtime']
