[package]
authors = ["Bholdus <https://github.com/bholdus>"]
edition = "2018"
homepage = "https://bholdus.com"
name = "runtime-chain-extension"
repository = "https://github.com/bholdus/bholdus-chain/"
version = "1.0.14"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enumflags2 = { version = "0.7.4" }
smallvec = "1.6.1"

[dependencies.codec]
default-features = false
features = ['derive', 'max-encoded-len']
package = 'parity-scale-codec'
version = '2.2.0'

[dependencies.scale-info]
default-features = false
features = ['derive']
version = '1.0'

[dependencies.frame-benchmarking]
default-features = false
git = 'https://github.com/bholdus/substrate.git'
optional = true
branch = 'bholdus-monthly-2021-11'
version = '4.0.0-dev'

[dependencies.frame-support]
default-features = false
git = 'https://github.com/bholdus/substrate.git'
branch = 'bholdus-monthly-2021-11'
version = '4.0.0-dev'

[dependencies.frame-system]
default-features = false
git = 'https://github.com/bholdus/substrate.git'
branch = 'bholdus-monthly-2021-11'
version = '4.0.0-dev'

[dependencies.sp-runtime]
default-features = false
git = 'https://github.com/bholdus/substrate.git'
branch = 'bholdus-monthly-2021-11'
version = '4.0.0-dev'

[dependencies.sp-std]
default-features = false
git = 'https://github.com/bholdus/substrate.git'
branch = 'bholdus-monthly-2021-11'
version = '4.0.0-dev'

[dependencies.sp-core]
default-features = false
git = 'https://github.com/bholdus/substrate.git'
branch = 'bholdus-monthly-2021-11'
version = '4.0.0-dev'

[dependencies.pallet-contracts]
default-features = false
git = 'https://github.com/bholdus/substrate.git'
branch = 'bholdus-monthly-2021-11'
version = '4.0.0-dev'

[dependencies.pallet-balances]
default-features = false
git = 'https://github.com/bholdus/substrate.git'
branch = 'bholdus-monthly-2021-11'
version = '4.0.0-dev'

[dependencies.pallet-randomness-collective-flip]
default-features = false
git = 'https://github.com/bholdus/substrate.git'
branch = 'bholdus-monthly-2021-11'
version = '4.0.0-dev'

[dependencies.sample-extension]
default-features = false
path = "../../pallets/pallet-integration/sample-extension"

[dependencies.integration-tokens]
default-features = false
path = "../../pallets/pallet-integration/tokens"

[dependencies.bholdus-currencies]
default-features = false
path = "../../pallets/currencies"


[dependencies.bholdus-primitives]
default-features = false
path = "../../primitives/bholdus"

[dependencies.bholdus-pallet-integration]
default-features = false
path = "../../pallets/pallet-integration"
package = 'pallet-integration'

[features]
default = ['std']
std = [
	'codec/std',
	'scale-info/std',
	'frame-support/std',
	'frame-system/std',
	'frame-benchmarking/std',
	'sp-std/std',
	'sp-runtime/std',
	'pallet-contracts/std',
	'pallet-balances/std',
	'pallet-randomness-collective-flip/std',
	'sample-extension/std',
	'integration-tokens/std',
	'bholdus-currencies/std',
	'bholdus-primitives/std',
	'bholdus-pallet-integration/std',
]
runtime-benchmarks = [
	'frame-benchmarking',
	"sp-runtime/runtime-benchmarks",
	"frame-system/runtime-benchmarks",]



