[package]
authors = ["Bholdus <https://github.com/bholdus>"]
edition = "2021"
homepage = "https://bholdus.com"
name = "runtime-chain-extension"
repository = "https://github.com/bholdus/bholdus-chain/"
version = "1.0.23"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enumflags2 = { version = "0.7.5" }
smallvec = "1.8.0"

[dependencies.codec]
default-features = false
features = ['derive', 'max-encoded-len']
package = 'parity-scale-codec'
version = '3.0.0'

[dependencies.scale-info]
default-features = false
features = ['derive']
version = '2.0.1'

[dependencies.frame-benchmarking]
default-features = false
git = "https://github.com/BHONetwork/substrate.git"
optional = true
branch = "bho-polkadot-v0.9.26"

[dependencies.frame-support]
default-features = false
git = "https://github.com/BHONetwork/substrate.git"
branch = "bho-polkadot-v0.9.26"

[dependencies.frame-system]
default-features = false
git = "https://github.com/BHONetwork/substrate.git"
branch = "bho-polkadot-v0.9.26"

[dependencies.sp-runtime]
default-features = false
git = "https://github.com/BHONetwork/substrate.git"
branch = "bho-polkadot-v0.9.26"

[dependencies.sp-std]
default-features = false
git = "https://github.com/BHONetwork/substrate.git"
branch = "bho-polkadot-v0.9.26"

[dependencies.sp-core]
default-features = false
git = "https://github.com/BHONetwork/substrate.git"
branch = "bho-polkadot-v0.9.26"

[dependencies.pallet-contracts]
default-features = false
git = "https://github.com/BHONetwork/substrate.git"
branch = "bho-polkadot-v0.9.26"

[dependencies.pallet-balances]
default-features = false
git = "https://github.com/BHONetwork/substrate.git"
branch = "bho-polkadot-v0.9.26"

[dependencies.pallet-randomness-collective-flip]
default-features = false
git = "https://github.com/BHONetwork/substrate.git"
branch = "bho-polkadot-v0.9.26"

[dependencies.bholdus-currencies]
default-features = false
path = "../../pallets/currencies"


[dependencies.common-primitives]
default-features = false
path = "../../primitives/common"

[features]
default = ['std']
std = [
	'codec/std',
	'scale-info/std',
	'frame-support/std',
	'frame-system/std',
	'frame-benchmarking/std',
	'sp-std/std',
	'sp-runtime/std',
	'pallet-contracts/std',
	'pallet-balances/std',
	'pallet-randomness-collective-flip/std',
	'bholdus-currencies/std',
	'common-primitives/std',
]
runtime-benchmarks = [
	'frame-benchmarking',
	"sp-runtime/runtime-benchmarks",
	"frame-system/runtime-benchmarks",]



