[package]
authors = ['Bholdus <https://github.com/bholdus>']
description = "Lixi App"
edition = "2021"
homepage = 'https://bholdus.com'
name = 'lixi'
license = "Apache-2.0"
readme = 'README.md'
repository = 'https://github.com/bholdus/bholdus-chain'
version = '4.0.0-dev'

[dependencies]
ink_primitives = { version = "3.0.0-rc7", default-features = false }
ink_metadata = { version = "3.0.0-rc7", default-features = false, features = ["derive"], optional = true }
ink_env = { version = "3.0.0-rc7", default-features = false, features = [ "ink-debug" ] }
ink_storage = { version = "3.0.0-rc7", default-features = false }
ink_lang = { version = "3.0.0-rc7", default-features = false }
ink_prelude = { version = "3.0.0-rc7", default-features = false }

scale = { package = "parity-scale-codec", version = "2.1", default-features = false, features = ["derive"] }
scale-info = { version = "1.0.0", default-features = false, features = ["derive"], optional = true }


# Needed until https://github.com/paritytech/ink/issues/364 is resolved.
[profile.release]
overflow-checks = false


[lib]
name = "lixiApp"
path = "lib.rs"
crate-type = [
# Used for normal contract Wasm blobs.
	"cdylib",
]

[features]
default = ["std"]
std = [
	"ink_metadata/std",
	"ink_env/std",
	"ink_storage/std",
	"ink_primitives/std",
	"ink_prelude/std",
	"scale/std",
	"scale-info",
	"scale-info/std",
]
ink-as-dependency = []

