[workspace]
members = [
    'node',
    'node/cli',
    'node/service',
    'rpc',
    'runtime/chain-extension',
    'runtime/ulas',
    'runtime/cygnus',
    'runtime/phoenix',
    'pallets/currencies',
    # 'pallets/dex',
    'pallets/support',
    'pallets/support/nft',
    'pallets/tokens',
    'pallets/non-fungible-token',
    # 'pallets/bridge/bsc',
     'pallets/bridge/native-transfer',
     'pallets/pallet-integration',
     'pallets/pallet-integration/sample-extension',
     'primitives/bholdus',
     'primitives/bsc',
]

exclude = [
    'smart-contracts/tokens'
]
[profile.release]
panic = 'unwind'

