[workspace]
members = [
    'node',
    'node/cli',
    'node/service',
    'rpc',
    'runtime/ulas',
    'runtime/cygnus',
    'runtime/phoenix',
    'pallets/currencies',
    # 'pallets/dex',
    'pallets/support',
    'pallets/support/nft',
    'pallets/tokens',
    'pallets/non-fungible-token',
    # 'pallets/bridge/bsc',
    'pallets/bridge/native-transfer',
    'pallets/bholdus-smart-contract',
    'primitives/bholdus',
    'primitives/bsc',
]

exclude = [
    'smart-contracts/inkextension'
]
[profile.release]
panic = 'unwind'

