[workspace]
members = [
    'node',
    'node/cli',
    'node/service',
    'rpc',
    'runtime/bholdus',
    'pallets/template',
    'pallets/bholdus-private-sales',
    'pallets/tokens',
    'pallets/dex'
]
[profile.release]
panic = 'unwind'
