[workspace]
members = [
    'node',
    'node/cli',
    'node/service',
    'rpc',
    'runtime/bholdus',
    'pallets/chainbridge',
    'pallets/chainbridge-transfer',
    'pallets/currencies',
    'pallets/dex',
    'pallets/support',
    'pallets/tokens',
    'pallets/bridge/bsc',
    'primitives/bholdus',
    'primitives/bsc'
]
[profile.release]
panic = 'unwind'
