[workspace]
members = [
    'node',
    'node/cli',
    'node/service',

    'primitives/bholdus',
    'primitives/bsc',

    'runtime/chain-extension',
    'runtime/ulas',
    'runtime/cygnus',
    'runtime/phoenix',

    'pallets/currencies',
    # 'pallets/dex',
    'pallets/support',
    'pallets/support/nft',
    'pallets/tokens',
    'pallets/non-fungible-token',
    # 'pallets/bridge/bsc',
    'pallets/bridge/native-transfer',
    'pallets/template',

    'precompiles/template',
    'precompiles/utils',

    'pallets/pallet-integration',
    'pallets/pallet-integration/sample-extension',
]

exclude = [
    'smart-contracts/tokens',
	'smart-contracts/lixi',
]

[profile.release]
panic = 'unwind'

