version: "3.2"

services:
  # dev:
  #   container_name: node-template
  #   image: paritytech/ci-linux:974ba3ac-20201006
  #   working_dir: /var/www/node-template
  #   ports:
  #     - "9944:9944"
  #   environment:
  #     - CARGO_HOME=/var/www/node-template/.cargo
  #   volumes:
  #     - .:/var/www/node-template
  #     - type: bind
  #       source: ./.local
  #       target: /root/.local
  #   command: bash -c "cargo build --release && ./target/release/node-template --dev --ws-external"

  build-wasm:
    build:
      context: .
      dockerfile: Dockerfile.build-wasm
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /bholdus:/bholdus
    environment:
      - CHAIN=phoenix
      - ARCHIVE_PATH=build-wasm-archive
    command: scripts/build_wasm.sh