FROM rust

# install docker & compose
COPY --from=docker:20.10.12 /usr/local/bin/docker /usr/bin/

# install shell tools
RUN apt update && apt install -y jq

# Substrate deps
RUN apt update && apt install -y git clang curl libssl-dev llvm libudev-dev 

# Srtool cli
RUN cargo install --locked --git https://github.com/chevdor/srtool-cli --tag v0.8.0

# Subwasm
RUN cargo install --locked --git https://github.com/chevdor/subwasm --tag v0.16.1

WORKDIR /bholdus
