FROM rust:1.56.1 as builder

RUN apt-get update && apt-get install -y git libclang-dev

WORKDIR /bholdus

COPY . .

RUN ./scripts/init.sh

RUN cargo build --release --features with-{{RELEASE_NETWORK}}-runtime,evm-tracing

RUN mv ./target/release/bholdus /usr/local/bin

FROM rust:1.56.1 as runner

COPY --from=builder /usr/local/bin/bholdus /usr/local/bin/bholdus

RUN  apt-get update && apt-get install python -y