[package]
authors = ["Bholdus <https://github.com/bholdus>"]
description = "Real world decentralized finance."
edition = "2018"
homepage = "https://bholdus.com"
name = "bholdus-service"
repository = "https://github.com/bholdus/bholdus-chain/"
version = "1.0.13"

[dependencies]
structopt = "0.3.8"
rand = "0.8.4"

async-trait = { version = "0.1.48" }
futures = { version = "0.3.9", features = ["compat"] }
hex-literal = "0.3.1"
serde = { version = "1.0.124", features = ["derive"] }
serde_json = "1.0.68"
codec = { package = "parity-scale-codec", version = "2.0.0" }
jsonrpc-core = "18.0.0"
jsonrpc-pubsub = "18.0.0"
tokio = { version = "1.13.0", features = ["macros", "sync"] }

beefy-gadget = { version = "4.0.0-dev", git = "https://github.com/bholdus/substrate", branch = "bholdus-monthly-2021-11" }
beefy-gadget-rpc = { version = "4.0.0-dev", git = "https://github.com/bholdus/substrate", branch = "bholdus-monthly-2021-11" }
beefy-primitives = { version = "4.0.0-dev", git = "https://github.com/bholdus/substrate", branch = "bholdus-monthly-2021-11" }

frame-benchmarking = { version = "4.0.0-dev", git = "https://github.com/bholdus/substrate.git", branch = "bholdus-monthly-2021-11" }
frame-system = { version = "4.0.0-dev", git = "https://github.com/bholdus/substrate.git", branch = "bholdus-monthly-2021-11" }
pallet-transaction-payment = { version = "4.0.0-dev", git = "https://github.com/bholdus/substrate.git", branch = "bholdus-monthly-2021-11" }
substrate-frame-rpc-system = { version = "4.0.0-dev", git = "https://github.com/bholdus/substrate.git", branch = "bholdus-monthly-2021-11" }
pallet-transaction-payment-rpc = { version = "4.0.0-dev", git = "https://github.com/bholdus/substrate.git", branch = "bholdus-monthly-2021-11" }
pallet-transaction-payment-rpc-runtime-api = { version = "4.0.0-dev", git = "https://github.com/bholdus/substrate.git", branch = "bholdus-monthly-2021-11" }
pallet-im-online = { version = "4.0.0-dev", git = "https://github.com/bholdus/substrate.git", branch = "bholdus-monthly-2021-11" }
pallet-contracts-rpc = { version = '4.0.0-dev', git = 'https://github.com/bholdus/substrate.git', branch = 'bholdus-monthly-2021-11' }
pallet-mmr-rpc = { version = '3.0.0', git = 'https://github.com/bholdus/substrate.git', branch = 'bholdus-monthly-2021-11' }

sc-basic-authorship = { version = "0.10.0-dev", git = "https://github.com/bholdus/substrate.git", branch = "bholdus-monthly-2021-11" }
sc-cli = { version = "0.10.0-dev", features = [
    "wasmtime",
], git = "https://github.com/bholdus/substrate.git", branch = "bholdus-monthly-2021-11" }
sc-client-api = { version = "4.0.0-dev", git = "https://github.com/bholdus/substrate.git", branch = "bholdus-monthly-2021-11" }
sc-consensus = { version = "0.10.0-dev", git = "https://github.com/bholdus/substrate.git", branch = "bholdus-monthly-2021-11" }
sc-executor = { version = "0.10.0-dev", features = [
    "wasmtime",
], git = "https://github.com/bholdus/substrate.git", branch = "bholdus-monthly-2021-11" }
sc-consensus-aura = { version = "0.10.0-dev", git = "https://github.com/bholdus/substrate.git", branch = "bholdus-monthly-2021-11" }
sc-consensus-uncles = { version = "0.10.0-dev", git = "https://github.com/bholdus/substrate.git", branch = "bholdus-monthly-2021-11" }
sc-consensus-epochs = { version = "0.10.0-dev", git = "https://github.com/bholdus/substrate.git", branch = "bholdus-monthly-2021-11" }
sc-consensus-slots = { version = "0.10.0-dev", git = "https://github.com/bholdus/substrate.git", branch = "bholdus-monthly-2021-11" }
sc-finality-grandpa = { version = "0.10.0-dev", git = "https://github.com/bholdus/substrate.git", branch = "bholdus-monthly-2021-11" }
sc-finality-grandpa-rpc = { version = "0.10.0-dev", git = "https://github.com/bholdus/substrate.git", branch = "bholdus-monthly-2021-11" }
sc-keystore = { version = "4.0.0-dev", git = "https://github.com/bholdus/substrate.git", branch = "bholdus-monthly-2021-11" }
sc-rpc = { version = "4.0.0-dev", git = "https://github.com/bholdus/substrate.git", branch = "bholdus-monthly-2021-11" }
sc-rpc-api = { version = "0.10.0-dev", git = "https://github.com/bholdus/substrate.git", branch = "bholdus-monthly-2021-11" }
sc-service = { version = "0.10.0-dev", features = [
    "wasmtime",
], git = "https://github.com/bholdus/substrate.git", branch = "bholdus-monthly-2021-11" }
sc-telemetry = { version = "4.0.0-dev", git = "https://github.com/bholdus/substrate.git", branch = "bholdus-monthly-2021-11" }
sc-transaction-pool = { version = "4.0.0-dev", git = "https://github.com/bholdus/substrate.git", branch = "bholdus-monthly-2021-11" }
sc-transaction-pool-api = { version = '4.0.0-dev', git = 'https://github.com/bholdus/substrate.git', branch = 'bholdus-monthly-2021-11' }
sc-network = { version = "0.10.0-dev", git = "https://github.com/bholdus/substrate.git", branch = "bholdus-monthly-2021-11" }
sc-authority-discovery = { version = "0.10.0-dev", git = "https://github.com/bholdus/substrate.git", branch = "bholdus-monthly-2021-11" }
sc-chain-spec = { version = "4.0.0-dev", git = "https://github.com/bholdus/substrate.git", branch = "bholdus-monthly-2021-11" }

sp-api = { version = "4.0.0-dev", git = "https://github.com/bholdus/substrate.git", branch = "bholdus-monthly-2021-11" }
sp-trie = { version = "4.0.0-dev", git = "https://github.com/bholdus/substrate.git", branch = "bholdus-monthly-2021-11" }
sp-block-builder = { version = "4.0.0-dev", git = "https://github.com/bholdus/substrate.git", branch = "bholdus-monthly-2021-11" }
frame-system-rpc-runtime-api = { version = "4.0.0-dev", git = "https://github.com/bholdus/substrate.git", branch = "bholdus-monthly-2021-11" }
sp-blockchain = { version = "4.0.0-dev", git = "https://github.com/bholdus/substrate.git", branch = "bholdus-monthly-2021-11" }
sp-consensus = { version = "0.10.0-dev", git = "https://github.com/bholdus/substrate.git", branch = "bholdus-monthly-2021-11" }
sp-consensus-aura = { version = "0.10.0-dev", git = "https://github.com/bholdus/substrate.git", branch = "bholdus-monthly-2021-11" }
sp-core = { version = "4.0.0-dev", git = "https://github.com/bholdus/substrate.git", branch = "bholdus-monthly-2021-11" }
sp-finality-grandpa = { version = "4.0.0-dev", git = "https://github.com/bholdus/substrate.git", branch = "bholdus-monthly-2021-11" }
sp-inherents = { version = "4.0.0-dev", git = "https://github.com/bholdus/substrate.git", branch = "bholdus-monthly-2021-11" }
sp-runtime = { version = "4.0.0-dev", git = "https://github.com/bholdus/substrate.git", branch = "bholdus-monthly-2021-11" }
sp-timestamp = { version = "4.0.0-dev", git = "https://github.com/bholdus/substrate.git", branch = "bholdus-monthly-2021-11" }
sp-authorship = { version = "4.0.0-dev", git = "https://github.com/bholdus/substrate.git", branch = "bholdus-monthly-2021-11" }
sp-transaction-pool = { version = "4.0.0-dev", git = "https://github.com/bholdus/substrate.git", branch = "bholdus-monthly-2021-11" }
sp-keystore = { version = "0.10.0-dev", git = "https://github.com/bholdus/substrate.git", branch = "bholdus-monthly-2021-11" }
sp-offchain = { version = "4.0.0-dev", git = "https://github.com/bholdus/substrate.git", branch = "bholdus-monthly-2021-11" }
sp-session = { version = "4.0.0-dev", git = "https://github.com/bholdus/substrate.git", branch = "bholdus-monthly-2021-11" }
sp-storage = { version = "4.0.0-dev", git = "https://github.com/bholdus/substrate.git", branch = "bholdus-monthly-2021-11" }
sp-authority-discovery = { version = "4.0.0-dev", git = "https://github.com/bholdus/substrate.git", branch = "bholdus-monthly-2021-11" }

fc-mapping-sync = { version = "2.0.0-dev", git = "https://github.com/Bholdus/frontier.git", branch = "bholdus-monthly-2021-11" }
fc-db = { version = "2.0.0-dev", git = "https://github.com/Bholdus/frontier.git", branch = "bholdus-monthly-2021-11" }
fc-rpc-core = { git = "https://github.com/Bholdus/frontier.git", branch = "bholdus-monthly-2021-11" }
fc-rpc = { git = "https://github.com/Bholdus/frontier.git", branch = "bholdus-monthly-2021-11" }
fp-rpc = { version = "3.0.0-dev", git = "https://github.com/Bholdus/frontier.git", branch = "bholdus-monthly-2021-11" }
pallet-ethereum = { git = "https://github.com/bholdus/frontier", branch = "bholdus-monthly-2021-11" }
bholdus-evm-rpc-debug = { path = "../../client/evm/rpc/debug" }
bholdus-evm-rpc-primitives-debug = { path = "../../primitives/evm/rpc/debug" }
bholdus-evm-rpc-trace = { path = "../../client/evm/rpc/trace" }
bholdus-evm-primitives-ext = { path = "../../primitives/evm/ext" }

ulas-runtime = { optional = true, path = "../../runtime/ulas" }
cygnus-runtime = { optional = true, path = "../../runtime/cygnus" }
phoenix-runtime = { optional = true, path = "../../runtime/phoenix" }
bholdus-primitives = { path = "../../primitives/bholdus" }

[features]
default = ["std"]
std = []
runtime-benchmarks = [
    "ulas-runtime/runtime-benchmarks",
    "cygnus-runtime/runtime-benchmarks",
    "phoenix-runtime/runtime-benchmarks",
]
try-runtime = [
    "ulas-runtime/try-runtime",
    "cygnus-runtime/try-runtime",
    "phoenix-runtime/try-runtime",
]

with-ulas-runtime = ["ulas-runtime"]
with-cygnus-runtime = ["cygnus-runtime"]
with-phoenix-runtime = ["phoenix-runtime"]
with-all-runtime = [
    "with-ulas-runtime",
    "with-cygnus-runtime",
    "with-phoenix-runtime",
]
