[package]
name = "bholdus-evm-tracer"
authors = ["Bholdus"]
edition = "2018"
homepage = "https://bholdus.com"
license = "GPL-3.0-only"
repository = "https://github.com/bholdus/bholdus-chain/"
version = "0.1.0"

[dependencies]

# Bholdus
evm-tracing-events = { path = "../../primitives/evm/rpc/evm-tracing-events", default-features = false, features = [
	"evm-tracing",
] }
bholdus-evm-primitives-ext = { path = "../../primitives/evm/ext", default-features = false }

# Substrate
codec = { package = "parity-scale-codec", version = "2.2", default-features = false }
sp-core = { git = "https://github.com/bholdus/substrate.git", branch = "bholdus-monthly-2021-11", default-features = false }
sp-io = { git = "https://github.com/bholdus/substrate.git", branch = "bholdus-monthly-2021-11", default-features = false }
sp-runtime = { git = "https://github.com/bholdus/substrate.git", branch = "bholdus-monthly-2021-11", default-features = false }
sp-std = { git = "https://github.com/bholdus/substrate.git", branch = "bholdus-monthly-2021-11", default-features = false }

# Frontier
ethereum-types = { version = "0.12.0", default-features = false }
evm = { version = "0.33.0", default-features = false, features = [
	"with-codec",
] }
evm-gasometer = { version = "0.33.0", default-features = false }
evm-runtime = { version = "0.33.0", default-features = false }
fp-evm = { git = "https://github.com/bholdus/frontier", branch = "bholdus-monthly-2021-11", default-features = false }
pallet-evm = { git = "https://github.com/bholdus/frontier", branch = "bholdus-monthly-2021-11", default-features = false }

[features]
default = ["std"]
std = [
	"codec/std",
	"ethereum-types/std",
	"evm-gasometer/std",
	"evm-runtime/std",
	"evm-tracing-events/std",
	"evm/std",
	"evm/with-serde",
	"fp-evm/std",
	"bholdus-evm-primitives-ext/std",
	"pallet-evm/std",
	"sp-core/std",
	"sp-runtime/std",
	"sp-std/std",
]
