[package]
name = "runtime-common"
version = "1.0.19"
description = "Common runtime code for all runtimes"
authors = ["Daniel Lam"]
edition = "2021"
license = "Unlicense"
publish = false

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
smallvec = "1.8.0"

frame-system = { default-features = false, git = "https://github.com/BHONetwork/substrate.git", branch = "bho-polkadot-v0.9.23" }
frame-support = { default-features = false, git = "https://github.com/BHONetwork/substrate.git", branch = "bho-polkadot-v0.9.23" }
sp-runtime = { default-features = false, git = "https://github.com/BHONetwork/substrate.git", branch = "bho-polkadot-v0.9.23" }

common-primitives = { default-features = false, path = "../../primitives/common" }

[features]
default = ["std"]
std = [
    "frame-system/std",
    "frame-support/std",

    "sp-runtime/std",
    
    "common-primitives/std",
]
