[package]
authors = ["Bholdus Technologies"]
description = "Integrate tokens pallet provides basic functions to interact with smart contract"
edition = '2018'
homepage = 'https://substrate.dev'
license = 'Unlicense'
name = "integration-tokens"
readme = 'README.md'
repository = 'https://github.com/bholdus/bholdus-chain.git'
version = '4.0.0-dev'

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
