[package]
name = "hyper-runtime"
version = "1.0.23"
authors = ["BHO Network <daniel.lam@bho.network>"]
edition = "2021"
license = "Unlicense"
homepage = "https://github.com/BHONetwork/bholdus-chain"
repository = "https://github.com/paritytech/bholdus-chain"
build = "build.rs"
publish = false

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }
scale-info = { version = "2.1.1", default-features = false, features = ["derive"] }

pallet-authorship = { git = "https://github.com/BHONetwork/substrate.git", branch = "bho-polkadot-v0.9.26", default-features = false }
pallet-balances = { git = "https://github.com/BHONetwork/substrate.git", branch = "bho-polkadot-v0.9.26", default-features = false }
frame-support = { git = "https://github.com/BHONetwork/substrate.git", branch = "bho-polkadot-v0.9.26", default-features = false }
pallet-randomness-collective-flip = { git = "https://github.com/BHONetwork/substrate.git", branch = "bho-polkadot-v0.9.26", default-features = false }
pallet-sudo = { git = "https://github.com/BHONetwork/substrate.git", branch = "bho-polkadot-v0.9.26", default-features = false }
frame-system = { git = "https://github.com/BHONetwork/substrate.git", branch = "bho-polkadot-v0.9.26", default-features = false }
frame-try-runtime = { git = "https://github.com/BHONetwork/substrate.git", branch = "bho-polkadot-v0.9.26", default-features = false, optional = true }
pallet-timestamp = { git = "https://github.com/BHONetwork/substrate.git", branch = "bho-polkadot-v0.9.26", default-features = false }
pallet-transaction-payment = { git = "https://github.com/BHONetwork/substrate.git", branch = "bho-polkadot-v0.9.26", default-features = false }
frame-executive = { git = "https://github.com/BHONetwork/substrate.git", branch = "bho-polkadot-v0.9.26", default-features = false }
sp-api = { git = "https://github.com/BHONetwork/substrate.git", branch = "bho-polkadot-v0.9.26", default-features = false }
sp-block-builder = { git = "https://github.com/BHONetwork/substrate.git", branch = "bho-polkadot-v0.9.26", default-features = false }
sp-core = { git = "https://github.com/BHONetwork/substrate.git", branch = "bho-polkadot-v0.9.26", default-features = false }
sp-inherents = { git = "https://github.com/BHONetwork/substrate.git", branch = "bho-polkadot-v0.9.26", default-features = false }
sp-offchain = { git = "https://github.com/BHONetwork/substrate.git", branch = "bho-polkadot-v0.9.26", default-features = false }
sp-runtime = { git = "https://github.com/BHONetwork/substrate.git", branch = "bho-polkadot-v0.9.26", default-features = false }
sp-session = { git = "https://github.com/BHONetwork/substrate.git", branch = "bho-polkadot-v0.9.26", default-features = false }
sp-std = { git = "https://github.com/BHONetwork/substrate.git", branch = "bho-polkadot-v0.9.26", default-features = false }
sp-transaction-pool = { git = "https://github.com/BHONetwork/substrate.git", branch = "bho-polkadot-v0.9.26", default-features = false }
sp-version = { git = "https://github.com/BHONetwork/substrate.git", branch = "bho-polkadot-v0.9.26", default-features = false }

# Used for the node's RPCs
frame-system-rpc-runtime-api = { git = "https://github.com/BHONetwork/substrate.git", branch = "bho-polkadot-v0.9.26", default-features = false }
pallet-transaction-payment-rpc-runtime-api = { git = "https://github.com/BHONetwork/substrate.git", branch = "bho-polkadot-v0.9.26", default-features = false }

# Used for runtime benchmarking
frame-benchmarking = { git = "https://github.com/BHONetwork/substrate.git", default-features = false, branch = "bho-polkadot-v0.9.26", optional = true }
frame-system-benchmarking = { git = "https://github.com/BHONetwork/substrate.git", default-features = false, branch = "bho-polkadot-v0.9.26", optional = true }
hex-literal = { version = "0.3.4", optional = true }

# Contracts specific packages
pallet-contracts = { git = "https://github.com/BHONetwork/substrate.git", branch = "bho-polkadot-v0.9.26", default-features = false }
pallet-contracts-primitives = { git = "https://github.com/BHONetwork/substrate.git", branch = "bho-polkadot-v0.9.26", default-features = false }
pallet-contracts-rpc-runtime-api = { git = "https://github.com/BHONetwork/substrate.git", branch = "bho-polkadot-v0.9.26", default-features = false }

[build-dependencies]
substrate-wasm-builder =  { git = "https://github.com/BHONetwork/substrate.git", branch = "bho-polkadot-v0.9.26" }

[features]
default = [
	"std",
	# temporarily enable unstable contracts features by default, remove this before using on a production chain.
	# "contracts-unstable-interface",
]
std = [
	"codec/std",
	"scale-info/std",
	"frame-executive/std",
	"frame-support/std",
	"frame-system-rpc-runtime-api/std",
	"frame-system/std",
	"pallet-authorship/std",
	"pallet-balances/std",
	"pallet-randomness-collective-flip/std",
	"pallet-sudo/std",
	"pallet-timestamp/std",
	"pallet-transaction-payment-rpc-runtime-api/std",
	"pallet-transaction-payment/std",
	"sp-api/std",
	"sp-block-builder/std",
	"sp-core/std",
	"sp-inherents/std",
	"sp-offchain/std",
	"sp-runtime/std",
	"sp-session/std",
	"sp-std/std",
	"sp-transaction-pool/std",
	"sp-version/std",
	"pallet-contracts/std",
	"pallet-contracts-primitives/std",
	"pallet-contracts-rpc-runtime-api/std",
]
runtime-benchmarks = [
	"frame-benchmarking/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"frame-system-benchmarking",
	"frame-system/runtime-benchmarks",
	"hex-literal",
	"pallet-balances/runtime-benchmarks",
	"pallet-timestamp/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
]
try-runtime = [
	"frame-executive/try-runtime",
	"frame-try-runtime",
	"frame-system/try-runtime",
	"pallet-balances/try-runtime",
	"pallet-randomness-collective-flip/try-runtime",
	"pallet-sudo/try-runtime",
	"pallet-timestamp/try-runtime",
	"pallet-transaction-payment/try-runtime",
]

# Make contract callable functions marked as __unstable__ available. Do not enable
# on live chains as those are subject to change.
contracts-unstable-interface = [
	"pallet-contracts/unstable-interface"
]
