// This file is part of Substrate.

// Copyright (C) 2021 Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Autogenerated weights for bholdus_memo
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2022-04-07, STEPS: `20`, REPEAT: 10, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("phoenix-dev"), DB CACHE: 128

// Executed Command:

// ./target/release/bholdus

// benchmark

// --chain

// phoenix-dev

// --execution

// wasm

// --wasm-execution

// compiled

// --pallet

// bholdus-memo

// --extrinsic

// *

// --steps

// 20

// --repeat

// 10

// --raw

// --output

// ./pallets/memo/src/weights.rs

// --template

// ./.maintain/frame-weight-template.hbs


#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weight functions needed for bholdus_memo.
pub trait WeightInfo {
	
	fn create(n: u32, s: u32, ) -> Weight;
	
}

/// Weights for bholdus_memo using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);

impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {

	
	
	// Storage: Timestamp Now (r:1 w:0)
	
	// Storage: Memo Memo (r:0 w:1)
	
	fn create(n: u32, s: u32, ) -> Weight {
		(14_063_000 as Weight)
			
			// Standard Error: 0
			.saturating_add((2_000 as Weight).saturating_mul(n as Weight))
			
			// Standard Error: 0
			.saturating_add((3_000 as Weight).saturating_mul(s as Weight))
			
			
			.saturating_add(T::DbWeight::get().reads(1 as Weight))
			
			
			
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
			
			
	}
	
}

// For backwards compatibility and tests
impl WeightInfo for () {
	
	
	// Storage: Timestamp Now (r:1 w:0)
	
	// Storage: Memo Memo (r:0 w:1)
	
	fn create(n: u32, s: u32, ) -> Weight {
		(14_063_000 as Weight)
			
			// Standard Error: 0
			.saturating_add((2_000 as Weight).saturating_mul(n as Weight))
			
			// Standard Error: 0
			.saturating_add((3_000 as Weight).saturating_mul(s as Weight))
			
			
			.saturating_add(RocksDbWeight::get().reads(1 as Weight))
			
			
			
			.saturating_add(RocksDbWeight::get().writes(1 as Weight))
			
			
	}
	
}