[package]
authors = ["Bholdus <https://github.com/bholdus>"]
edition = "2018"
homepage = "https://bholdus.com"
name = "phoenix-runtime"
repository = "https://github.com/bholdus/bholdus-chain/"
version = "1.0.18"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[build-dependencies.substrate-wasm-builder]
git = "https://github.com/BHONetwork/substrate.git"
branch = "bho-polkadot-v0.9.18"
version = "5.0.0-dev"

[dependencies]
codec = { version = "3.0.0", package = "parity-scale-codec", default-features = false, features = [
	"derive",
	"max-encoded-len",
] }
scale-info = { version = "2.0.1", default-features = false, features = [
	"derive",
] }
hex-literal = { version = "0.3.1", optional = true }
log = { version = "0.4", default-features = false }
smallvec = "1.8.0"
rlp = { version = "0.5", optional = true, default-features = false }
sha3 = { version = "0.8", optional = true, default-features = false }

# FRAME dependencies
frame-benchmarking = { git = "https://github.com/BHONetwork/substrate.git", default-features = false, optional = true, branch = "bho-polkadot-v0.9.18" }
frame-executive = { git = "https://github.com/BHONetwork/substrate.git", default-features = false, branch = "bho-polkadot-v0.9.18" }
frame-support = { git = "https://github.com/BHONetwork/substrate.git", default-features = false, branch = "bho-polkadot-v0.9.18" }
frame-system = { git = "https://github.com/BHONetwork/substrate.git", default-features = false, branch = "bho-polkadot-v0.9.18" }
frame-system-benchmarking = { git = "https://github.com/BHONetwork/substrate.git", default-features = false, optional = true, branch = "bho-polkadot-v0.9.18" }
frame-system-rpc-runtime-api = { git = "https://github.com/BHONetwork/substrate.git", default-features = false, branch = "bho-polkadot-v0.9.18" }
frame-election-provider-support = { git = "https://github.com/BHONetwork/substrate.git", default-features = false, branch = "bho-polkadot-v0.9.18" }
frame-try-runtime = { optional = true, git = "https://github.com/BHONetwork/substrate.git", default-features = false, branch = "bho-polkadot-v0.9.18" }

pallet-babe = { git = "https://github.com/BHONetwork/substrate.git", default-features = false, branch = "bho-polkadot-v0.9.18" }
pallet-balances = { git = "https://github.com/BHONetwork/substrate.git", default-features = false, branch = "bho-polkadot-v0.9.18" }
pallet-grandpa = { git = "https://github.com/BHONetwork/substrate.git", default-features = false, branch = "bho-polkadot-v0.9.18" }
pallet-randomness-collective-flip = { git = "https://github.com/BHONetwork/substrate.git", default-features = false, branch = "bho-polkadot-v0.9.18" }
pallet-sudo = { git = "https://github.com/BHONetwork/substrate.git", default-features = false, branch = "bho-polkadot-v0.9.18" }
pallet-timestamp = { git = "https://github.com/BHONetwork/substrate.git", default-features = false, branch = "bho-polkadot-v0.9.18" }
pallet-transaction-payment = { git = "https://github.com/BHONetwork/substrate.git", default-features = false, branch = "bho-polkadot-v0.9.18" }
pallet-transaction-payment-rpc-runtime-api = { git = "https://github.com/BHONetwork/substrate.git", default-features = false, branch = "bho-polkadot-v0.9.18" }
pallet-staking = { git = "https://github.com/BHONetwork/substrate.git", default-features = false, branch = "bho-polkadot-v0.9.18" }
pallet-staking-reward-curve = { git = "https://github.com/BHONetwork/substrate.git", default-features = false, branch = "bho-polkadot-v0.9.18" }
pallet-aura = { git = "https://github.com/BHONetwork/substrate.git", default-features = false, branch = "bho-polkadot-v0.9.18" }
pallet-session = { git = "https://github.com/BHONetwork/substrate.git", default-features = false, branch = "bho-polkadot-v0.9.18" }
pallet-im-online = { git = "https://github.com/BHONetwork/substrate.git", default-features = false, branch = "bho-polkadot-v0.9.18" }
pallet-authority-discovery = { git = "https://github.com/BHONetwork/substrate.git", default-features = false, branch = "bho-polkadot-v0.9.18" }
pallet-offences = { git = "https://github.com/BHONetwork/substrate.git", default-features = false, branch = "bho-polkadot-v0.9.18" }
pallet-treasury = { git = "https://github.com/BHONetwork/substrate.git", default-features = false, branch = "bho-polkadot-v0.9.18" }
pallet-utility = { git = "https://github.com/BHONetwork/substrate.git", default-features = false, branch = "bho-polkadot-v0.9.18" }
pallet-collective = { git = "https://github.com/BHONetwork/substrate.git", default-features = false, branch = "bho-polkadot-v0.9.18" }
pallet-election-provider-multi-phase = { git = "https://github.com/BHONetwork/substrate.git", default-features = false, branch = "bho-polkadot-v0.9.18" }
pallet-indices = { git = "https://github.com/BHONetwork/substrate.git", default-features = false, branch = "bho-polkadot-v0.9.18" }
pallet-bounties = { git = "https://github.com/BHONetwork/substrate.git", default-features = false, branch = "bho-polkadot-v0.9.18" }
pallet-authorship = { git = "https://github.com/BHONetwork/substrate.git", default-features = false, branch = "bho-polkadot-v0.9.18" }
pallet-contracts = { git = "https://github.com/BHONetwork/substrate.git", default-features = false, branch = "bho-polkadot-v0.9.18" }
pallet-contracts-rpc-runtime-api = { git = "https://github.com/BHONetwork/substrate.git", default-features = false, branch = "bho-polkadot-v0.9.18" }
pallet-contracts-primitives = { git = "https://github.com/BHONetwork/substrate.git", default-features = false, branch = "bho-polkadot-v0.9.18" }
pallet-mmr = { git = "https://github.com/BHONetwork/substrate.git", default-features = false, branch = "bho-polkadot-v0.9.18" }
pallet-scheduler = { git = "https://github.com/BHONetwork/substrate.git", default-features = false, branch = "bho-polkadot-v0.9.18" }
pallet-proxy = { git = "https://github.com/BHONetwork/substrate.git", default-features = false, branch = "bho-polkadot-v0.9.18" }
pallet-identity = { git = "https://github.com/BHONetwork/substrate.git", default-features = false, branch = "bho-polkadot-v0.9.18" }
pallet-recovery = { git = "https://github.com/BHONetwork/substrate.git", default-features = false, branch = "bho-polkadot-v0.9.18" }
pallet-bags-list = { git = "https://github.com/BHONetwork/substrate.git", default-features = false, branch = "bho-polkadot-v0.9.18" }
pallet-multisig = { git = "https://github.com/BHONetwork/substrate.git", default-features = false, branch = "bho-polkadot-v0.9.18" }
beefy-primitives = { git = "https://github.com/BHONetwork/substrate.git", default-features = false, branch = "bho-polkadot-v0.9.18" }
pallet-beefy = { git = "https://github.com/BHONetwork/substrate.git", default-features = false, branch = "bho-polkadot-v0.9.18" }
pallet-beefy-mmr = { git = "https://github.com/BHONetwork/substrate.git", default-features = false, branch = "bho-polkadot-v0.9.18" }
pallet-preimage = { git = "https://github.com/BHONetwork/substrate.git", default-features = false, branch = "bho-polkadot-v0.9.18" }
pallet-child-bounties = { git = "https://github.com/BHONetwork/substrate.git", default-features = false, branch = "bho-polkadot-v0.9.18" }

# Frontier
pallet-evm = { default-features = false, version = "6.0.0-dev", git = "https://github.com/BHONetwork/frontier.git", branch = "bho-polkadot-v0.9.18" }
pallet-ethereum = { default-features = false, git = "https://github.com/BHONetwork/frontier.git", branch = "bho-polkadot-v0.9.18" }
pallet-base-fee = { default-features = false, version = "1.0.0-dev", git = "https://github.com/BHONetwork/frontier.git", branch = "bho-polkadot-v0.9.18" }
fp-self-contained = { default-features = false, version = "1.0.0-dev", git = "https://github.com/BHONetwork/frontier.git", branch = "bho-polkadot-v0.9.18" }
fp-rpc = { default-features = false, version = "3.0.0-dev", git = "https://github.com/BHONetwork/frontier.git", branch = "bho-polkadot-v0.9.18" }
fp-evm = { default-features = false, version = "3.0.0-dev", git = "https://github.com/BHONetwork/frontier.git", branch = "bho-polkadot-v0.9.18" }
pallet-evm-precompile-blake2 = { git = "https://github.com/BHONetwork/frontier.git", branch = "bho-polkadot-v0.9.18", default-features = false }
pallet-evm-precompile-bn128 = { git = "https://github.com/BHONetwork/frontier.git", branch = "bho-polkadot-v0.9.18", default-features = false }
pallet-evm-precompile-dispatch = { git = "https://github.com/BHONetwork/frontier.git", branch = "bho-polkadot-v0.9.18", default-features = false }
pallet-evm-precompile-modexp = { git = "https://github.com/BHONetwork/frontier.git", branch = "bho-polkadot-v0.9.18", default-features = false }
pallet-evm-precompile-sha3fips = { git = "https://github.com/BHONetwork/frontier.git", branch = "bho-polkadot-v0.9.18", default-features = false }
pallet-evm-precompile-simple = { git = "https://github.com/BHONetwork/frontier.git", branch = "bho-polkadot-v0.9.18", default-features = false }
bholdus-evm-rpc-primitives-debug = { path = "../../primitives/evm/rpc/debug", default-features = false }
evm-tracing-events = { path = "../../primitives/evm/rpc/evm-tracing-events", optional = true, default-features = false }
bholdus-evm-tracer = { path = "../evm-tracer", optional = true, default-features = false }

# Substrate primitives
sp-api = { git = "https://github.com/BHONetwork/substrate.git", default-features = false, branch = "bho-polkadot-v0.9.18" }
sp-block-builder = { git = "https://github.com/BHONetwork/substrate.git", default-features = false, branch = "bho-polkadot-v0.9.18" }
sp-core = { git = "https://github.com/BHONetwork/substrate.git", default-features = false, branch = "bho-polkadot-v0.9.18" }
sp-inherents = { git = "https://github.com/BHONetwork/substrate.git", default-features = false, branch = "bho-polkadot-v0.9.18" }
sp-runtime = { git = "https://github.com/BHONetwork/substrate.git", default-features = false, branch = "bho-polkadot-v0.9.18" }
sp-offchain = { git = "https://github.com/BHONetwork/substrate.git", default-features = false, branch = "bho-polkadot-v0.9.18" }
sp-session = { git = "https://github.com/BHONetwork/substrate.git", default-features = false, branch = "bho-polkadot-v0.9.18" }
sp-std = { git = "https://github.com/BHONetwork/substrate.git", default-features = false, branch = "bho-polkadot-v0.9.18" }
sp-transaction-pool = { git = "https://github.com/BHONetwork/substrate.git", default-features = false, branch = "bho-polkadot-v0.9.18" }
sp-version = { git = "https://github.com/BHONetwork/substrate.git", default-features = false, branch = "bho-polkadot-v0.9.18" }
sp-staking = { git = "https://github.com/BHONetwork/substrate.git", default-features = false, branch = "bho-polkadot-v0.9.18" }
sp-authority-discovery = { git = "https://github.com/BHONetwork/substrate.git", default-features = false, branch = "bho-polkadot-v0.9.18" }
sp-npos-elections = { git = "https://github.com/BHONetwork/substrate.git", default-features = false, branch = "bho-polkadot-v0.9.18" }
sp-consensus-aura = { git = "https://github.com/BHONetwork/substrate.git", default-features = false, branch = "bho-polkadot-v0.9.18" }
sp-io = { git = "https://github.com/BHONetwork/substrate.git", default-features = false, branch = "bho-polkadot-v0.9.18" }

# local dependencies
common-primitives = { path = "../../primitives/common", default-features = false }
runtime-common = { path = "../common", default-features = false }
bholdus-tokens = { path = "../../pallets/tokens", default-features = false }
bholdus-memo = { path = "../../pallets/memo", default-features = false }
bholdus-nft = { path = "../../pallets/non-fungible-token", default-features = false }
bholdus-nft-marketplace = { path = "../../pallets/nft-marketplace", default-features = false }
bholdus-support-nft = { package = "support-nft", path = "../../pallets/support/nft", default-features = false }
bholdus-support-nft-marketplace = { package = "support-nft-marketplace", path = "../../pallets/support/nft-marketplace", default-features = false }
bholdus-support = { path = "../../pallets/support", default-features = false }
bholdus-currencies = { path = "../../pallets/currencies", default-features = false }
bholdus-bridge-native-transfer = { path = "../../pallets/bridge/native-transfer", default-features = false }

runtime-chain-extension = { path = "../chain-extension", default-features = false }

[features]
default = ["std"]
manual-seal = []
runtime-benchmarks = [
	"frame-benchmarking",
	"frame-support/runtime-benchmarks",
	"frame-system-benchmarking",
	"frame-system/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	'pallet-balances/runtime-benchmarks',
	'pallet-timestamp/runtime-benchmarks',
	'pallet-collective/runtime-benchmarks',
	"hex-literal",

	"pallet-ethereum/runtime-benchmarks",

	"bholdus-bridge-native-transfer/runtime-benchmarks",
	"bholdus-memo/runtime-benchmarks",
	"bholdus-tokens/runtime-benchmarks",
	"bholdus-nft/runtime-benchmarks",
]

contracts-unstable-interface = [
	"pallet-contracts/unstable-interface"
]

std = [
	"codec/std",
	"scale-info/std",
	"frame-executive/std",
	"frame-support/std",
	"frame-system-rpc-runtime-api/std",
	"frame-system/std",
	"frame-try-runtime/std",
	"pallet-babe/std",
	"pallet-balances/std",
	"pallet-grandpa/std",
	"pallet-randomness-collective-flip/std",
	"pallet-sudo/std",
	"pallet-timestamp/std",
	"pallet-transaction-payment-rpc-runtime-api/std",
	"pallet-transaction-payment/std",
	"pallet-staking/std",
	"pallet-aura/std",
	"pallet-session/std",
	"pallet-im-online/std",
	"pallet-authority-discovery/std",
	"pallet-offences/std",
	"pallet-treasury/std",
	"pallet-utility/std",
	"pallet-collective/std",
	"pallet-election-provider-multi-phase/std",
	"pallet-indices/std",
	"pallet-bounties/std",
	"pallet-authorship/std",
	"pallet-contracts/std",
	"pallet-contracts-rpc-runtime-api/std",
	"pallet-mmr/std",
	"pallet-multisig/std",
	"pallet-proxy/std",
	"pallet-identity/std",
	"pallet-recovery/std",
	"pallet-beefy/std",
	"pallet-beefy-mmr/std",
	"pallet-preimage/std",
	"pallet-child-bounties/std",

	"common-primitives/std",
	"runtime-common/std",
	"bholdus-tokens/std",
	"bholdus-memo/std",
	"bholdus-nft/std",
	"bholdus-nft-marketplace/std",
	"bholdus-support-nft/std",
	"bholdus-support-nft-marketplace/std",
	"bholdus-support/std",
	"bholdus-currencies/std",
	"bholdus-bridge-native-transfer/std",
	"sp-api/std",
	"sp-block-builder/std",
	"sp-core/std",
	"sp-inherents/std",
	"sp-offchain/std",
	"sp-runtime/std",
	"sp-session/std",
	"sp-std/std",
	"sp-transaction-pool/std",
	"sp-version/std",
	"sp-staking/std",
	"sp-authority-discovery/std",
	"sp-npos-elections/std",
	"sp-consensus-aura/std",
	"sp-io/std",

	# Frontier
	"pallet-evm/std",
	"pallet-evm-precompile-blake2/std",
	"pallet-evm-precompile-bn128/std",
	"pallet-evm-precompile-dispatch/std",
	"pallet-evm-precompile-modexp/std",
	"pallet-evm-precompile-sha3fips/std",
	"pallet-evm-precompile-simple/std",
	"pallet-ethereum/std",
	"pallet-base-fee/std",
	"fp-self-contained/std",
	'fp-rpc/std',
	'fp-evm/std',
	"bholdus-evm-rpc-primitives-debug/std",
	"evm-tracing-events/std",
	"bholdus-evm-tracer/std",

	"runtime-chain-extension/std",
]

evm-tracing = ["evm-tracing-events", "bholdus-evm-tracer", "rlp", "sha3"]

try-runtime = [
	"frame-try-runtime",
	"frame-executive/try-runtime",
	"frame-system/try-runtime",

	"pallet-babe/try-runtime",
	"pallet-balances/try-runtime",
	"pallet-grandpa/try-runtime",
	"pallet-randomness-collective-flip/try-runtime",
	"pallet-sudo/try-runtime",
	"pallet-timestamp/try-runtime",
	"pallet-transaction-payment/try-runtime",
	"pallet-staking/try-runtime",
	"pallet-aura/try-runtime",
	"pallet-session/try-runtime",
	"pallet-im-online/try-runtime",
	"pallet-authority-discovery/try-runtime",
	"pallet-offences/try-runtime",
	"pallet-treasury/try-runtime",
	"pallet-utility/try-runtime",
	"pallet-collective/try-runtime",
	"pallet-election-provider-multi-phase/try-runtime",
	"pallet-indices/try-runtime",
	"pallet-bounties/try-runtime",
	"pallet-authorship/try-runtime",
	"pallet-contracts/try-runtime",
	"pallet-mmr/try-runtime",
	"pallet-multisig/try-runtime",
	"pallet-proxy/try-runtime",
	"pallet-identity/try-runtime",
	"pallet-recovery/try-runtime",

	"bholdus-bridge-native-transfer/try-runtime",
	"bholdus-memo/try-runtime",
]
