[package]
name = "sample"
version = "0.1.0"
authors = ["Vu Hoang <vuhoang2119@gmail.com>"]
edition = "2018"
resolver = "2"

[dependencies]
ink_primitives = { version = "3.0.0-rc7", default-features = false }
ink_metadata = { version = "3.0.0-rc7", default-features = false, features = ["derive"], optional = true }
ink_env = { version = "3.0.0-rc7", default-features = false, features = [ "ink-debug" ] }
ink_storage = { version = "3.0.0-rc7", default-features = false }
ink_lang = { version = "3.0.0-rc7", default-features = false }
ink_prelude = { version = "3.0.0-rc7", default-features = false }

scale = { package = "parity-scale-codec", version = "2.1", default-features = false, features = ["derive"] }
scale-info = { version = "1.0.0", default-features = false, features = ["derive"], optional = true }
# Never use this crate outside the off-chain environment!
rand = { version = "0.8", default-features = false, features = ["alloc"], optional = true }


# Needed until https://github.com/paritytech/ink/issues/364 is resolved.
[profile.release]
overflow-checks = false


[lib]
name = "extension"
path = "lib.rs"
crate-type = [
# Used for normal contract Wasm blobs.
	"cdylib",
]

[features]
default = ["std"]
std = [
	"ink_metadata/std",
	"ink_env/std",
	"ink_storage/std",
	"ink_primitives/std",
	"ink_prelude/std",
	"scale/std",
	"scale-info",
	"scale-info/std",
	"rand",
	"rand/std",
	"rand/std_rng",
]
ink-as-dependency = []
