[package]
name = "bholdus-client-evm-tracing"
authors = ["Bholdus"]
edition = "2018"
homepage = "https://bholdus.com"
license = "GPL-3.0-only"
repository = "https://github.com/Bholdus/bholdus-chain/"
version = "1.0.18"

[dependencies]
ethereum-types = { version = "0.13.1" }
hex = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }

# Bholdus
evm-tracing-events = { path = "../../../primitives/evm/rpc/evm-tracing-events" }
bholdus-evm-rpc-primitives-debug = { path = "../../../primitives/evm/rpc/debug" }

# Substrate
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false }
sp-std = { git = "https://github.com/BHONetwork/substrate", branch = "bho-polkadot-v0.9.18" }
