[package]
name = "bholdus-evm-primitives-ext"
authors = ["Bholdus"]
edition = "2018"
homepage = "https://bholdus.com"
license = "GPL-3.0-only"
repository = "https://github.com/bholdus/bholdus-chain/"
version = "1.0.15"

[dependencies]
ethereum-types = { version = "0.12.0", default-features = false }

# Substrate
evm-tracing-events = { path = "../rpc/evm-tracing-events", default-features = false }

# Substrate
codec = { package = "parity-scale-codec", version = "2.2", default-features = false }
sp-externalities = { git = "https://github.com/bholdus/substrate", branch = "bholdus-monthly-2021-11", default-features = false }
sp-runtime-interface = { git = "https://github.com/bholdus/substrate", branch = "bholdus-monthly-2021-11", default-features = false }
sp-std = { git = "https://github.com/bholdus/substrate", branch = "bholdus-monthly-2021-11", default-features = false }

[features]
default = ["std"]
std = [
	"codec/std",
	"ethereum-types/std",
	"evm-tracing-events/std",
	"sp-externalities/std",
	"sp-runtime-interface/std",
	"sp-std/std",
]
