[package]
name = "bholdus-evm-rpc-trace"
authors = ["Bholdus"]
edition = "2021"
homepage = "https://bholdus.com"
license = "GPL-3.0-only"
repository = "https://github.com/Bholdus/bholdus-chain/"
version = "1.0.22"

[dependencies]
ethereum = { version = "0.12.0", features = ["with-codec"] }
ethereum-types = "0.13.1"
futures = { version = "0.3" }
jsonrpc-core = "18.0.0"
serde = { version = "1.0", features = ["derive"] }
sha3 = "0.9"
tokio = { version = "1.10", features = ["sync", "time"] }
tracing = "0.1.32"

# Bholdus
bholdus-client-evm-tracing = { path = "../../evm-tracing" }
bholdus-evm-rpc-core-trace = { path = "../../rpc-core/trace" }
bholdus-evm-rpc-core-types = { path = "../../rpc-core/types" }
bholdus-evm-rpc-primitives-debug = { path = "../../../../primitives/evm/rpc/debug" }

# Substrate
sc-client-api = { git = "https://github.com/BHONetwork/substrate", branch = "bho-polkadot-v0.9.26" }
sc-network = { git = "https://github.com/BHONetwork/substrate", branch = "bho-polkadot-v0.9.26" }
sc-utils = { git = "https://github.com/BHONetwork/substrate", branch = "bho-polkadot-v0.9.26" }
sp-api = { git = "https://github.com/BHONetwork/substrate", branch = "bho-polkadot-v0.9.26" }
sp-block-builder = { git = "https://github.com/BHONetwork/substrate", branch = "bho-polkadot-v0.9.26" }
sp-blockchain = { git = "https://github.com/BHONetwork/substrate", branch = "bho-polkadot-v0.9.26" }
sp-io = { git = "https://github.com/BHONetwork/substrate", branch = "bho-polkadot-v0.9.26" }
sp-runtime = { git = "https://github.com/BHONetwork/substrate", branch = "bho-polkadot-v0.9.26" }
sp-std = { git = "https://github.com/BHONetwork/substrate", branch = "bho-polkadot-v0.9.26" }
sp-transaction-pool = { git = "https://github.com/BHONetwork/substrate", branch = "bho-polkadot-v0.9.26" }

# Frontier
fc-consensus = { git = "https://github.com/BHONetwork/frontier.git", branch = "bho-polkadot-v0.9.26" }
fc-rpc = { git = "https://github.com/BHONetwork/frontier.git", branch = "bho-polkadot-v0.9.26", features = ["rpc_binary_search_estimate"] }
fc-rpc-core = { git = "https://github.com/BHONetwork/frontier.git", branch = "bho-polkadot-v0.9.26" }
fp-rpc = { git = "https://github.com/BHONetwork/frontier.git", branch = "bho-polkadot-v0.9.26" }
