[package]
authors = ["Bholdus Network <hello@bholdus.network>"]
description = "A Substrate Runtime module that is able to verify bsc(Binance Smart Chain) headers and authority set finality."
edition = "2018"
homepage = "https://bholdus.com/"
license = "GPL-3.0"
name = "bholdus-bridge-bsc"
readme = "README.md"
repository = "https://github.com/bholdus/bholdus-chain/"
version = "4.0.0-dev"

[dependencies]
# crates.io
codec = { package = "parity-scale-codec", version = "2.1.1", default-features = false }
scale-info = { version = "1.0", default-features = false, features = [
	"derive",
] }
# darwinia-network
bsc-primitives = { default-features = false, path = "../../../primitives/bsc" }
# paritytech
frame-support = { default-features = false, git = "https://github.com/bholdus/substrate", branch = 'bholdus-monthly-2021-11' }
frame-system = { default-features = false, git = "https://github.com/bholdus/substrate", branch = 'bholdus-monthly-2021-11' }
sp-core = { default-features = false, git = "https://github.com/bholdus/substrate", branch = 'bholdus-monthly-2021-11' }
sp-io = { default-features = false, git = "https://github.com/bholdus/substrate", branch = 'bholdus-monthly-2021-11' }
sp-runtime = { default-features = false, git = "https://github.com/bholdus/substrate", branch = 'bholdus-monthly-2021-11' }
sp-std = { default-features = false, git = "https://github.com/bholdus/substrate", branch = 'bholdus-monthly-2021-11' }
[dev-dependencies]
# crates.io
array-bytes = { version = "1.4.1" }
serde_json = { version = "1.0.66" }
# paritytech
pallet-timestamp = { git = "https://github.com/bholdus/substrate", branch = 'bholdus-monthly-2021-11' }

[features]
default = ["std"]

std = [
	# crates.io
	"codec/std",
	"scale-info/std",
	# darwinia-network
	"bsc-primitives/std",
	# paritytech
	"frame-support/std",
	"frame-system/std",
	"sp-core/std",
	"sp-io/std",
	"sp-runtime/std",
	"sp-std/std",
]
