[package]
name = "sample-extension"
version = "1.0.15"
authors = ["Vu hoang <vuhoang2119@gmail.com>"]
edition = "2018"

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

# Substrate dependencies
[dependencies]
codec = { default-features = false, features = [
	"derive",
		"max-encoded-len",
], package = "parity-scale-codec", version = "2.2.0" }
scale-info = { default-features = false, features = [
	'derive',
], version = '1.0' }
frame-benchmarking = { default-features = false, git = 'https://github.com/bholdus/substrate.git', optional = true, branch = 'bholdus-monthly-2021-11', version = '4.0.0-dev' }
frame-support = { default-features = false, git = 'https://github.com/bholdus/substrate.git', branch = 'bholdus-monthly-2021-11', version = '4.0.0-dev' }
frame-system = { default-features = false, git = 'https://github.com/bholdus/substrate.git', branch = 'bholdus-monthly-2021-11', version = '4.0.0-dev' }
pallet-contracts = { version = "4.0.0-dev", git = "https://github.com/bholdus/substrate.git", default-features = false, branch = "bholdus-monthly-2021-11" }

[dependencies.sp-std]
default-features = false
git = 'https://github.com/bholdus/substrate.git'
branch = 'bholdus-monthly-2021-11'
version = '4.0.0-dev'

[dependencies.sp-runtime]
default-features = false
git = 'https://github.com/bholdus/substrate.git'
branch = 'bholdus-monthly-2021-11'
version = '4.0.0-dev'

# Local dependencies
[dependencies.bholdus-primitives]
default-features = false
path = '../../../primitives/bholdus'

[dependencies.bholdus-support]
default-features = false
path = '../../support'


[dev-dependencies]
serde = '1.0.119'
sp-core = { default-features = false, git = 'https://github.com/bholdus/substrate.git', branch = 'bholdus-monthly-2021-11', version = '4.0.0-dev' }
sp-io = { default-features = false, git = 'https://github.com/bholdus/substrate.git', branch = 'bholdus-monthly-2021-11', version = '4.0.0-dev' }
sp-runtime = { default-features = false, git = 'https://github.com/bholdus/substrate.git', branch = 'bholdus-monthly-2021-11', version = '4.0.0-dev' }


[features]
default = ['std']
runtime-benchmarks = ['frame-benchmarking']
std = [
	'codec/std',
	'scale-info/std',
	'frame-support/std',
	'frame-system/std',
	'frame-benchmarking/std',
	"sp-std/std",
	"sp-runtime/std",
	"pallet-contracts/std",
	"bholdus-primitives/std",
	"bholdus-support/std",
]
try-runtime = ['frame-support/try-runtime']
