name: Test Cygnus
on:
  pull_request:
    branches:
      - cygnus-beta
    paths-ignore:
      - "**/README.md"
  push:
    branches:
      - cygnus-beta
    paths-ignore:
      - "**/README.md"
  workflow_dispatch:
jobs:
  clean-up-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}
  checks-and-tests:
    runs-on: ubuntu-latest
    env:
      SCCACHE_CACHE_SIZE: "50G"
      CARGO_INCREMENTAL: 0
    needs: clean-up-actions
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2021-11-07
          components: rustfmt
          target: wasm32-unknown-unknown
          default: true
      - name: Run runtime tests
        run: make test-cygnus-runtime
      - name: Run benchmarking tests
        run: make test-cygnus-benchmarking
      - name: Check try-runtime
        run: make check-cygnus-try-runtime
