[package]
name = "bholdus-evm-rpc-core-types"
authors = ["bholdus"]
edition = "2021"
homepage = "https://bholdus.com"
license = "GPL-3.0-only"
repository = "https://github.com/bholdus/bholdus-chain/"
version = "1.0.19"

[dependencies]
ethereum-types = "0.13.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
