[package]
name = "bholdus-evm-rpc-core-types"
authors = ["bholdus"]
edition = "2018"
homepage = "https://bholdus.com"
license = "GPL-3.0-only"
repository = "https://github.com/bholdus/bholdus-chain/"
version = "0.1.0"

[dependencies]
ethereum-types = "0.12.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
